### ISSUE TITLE
build broken on mac os and linux

### ISSUE THREAD

**Issue by agrippa** [habanero-rice/hclib#26]
With one of the recent merges, I'm getting the following error message on both Mac OS and Linux machines:

libtool: compile:  g++ -DPACKAGE_NAME=\"hclib\" -DPACKAGE_TARNAME=\"hclib\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"hclib 0.1\"" -DPACKAGE_BUGREPORT=\"vivekk@rice.edu\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I../../src -Wall -g -O3 -std=c++11 -I../../inc -I../../src/inc -I../../src/fcontext -DHC_ASSERTION_CHECK -DHC_COMM_WORKER_STATS -I/home/jmg3/libxml2/include/libxml2 -Wall -g -O3 -std=c++11 -MT libhclib_la-hclib_cpp.lo -MD -MP -MF .deps/libhclib_la-hclib_cpp.Tpo -c ../../src/hclib_cpp.cpp  -fPIC -DPIC -o .libs/libhclib_la-hclib_cpp.o
In file included from ../../inc/hclib_promise.h:5:0,
                 from ../../inc/hclib-async.h:42,
                 from ../../inc/hclib_cpp.h:6,
                 from ../../src/hclib_cpp.cpp:1:
../../inc/hclib_future.h:14:20: error: ‘is_trivially_copyable’ is not a member of ‘std’
     HASSERT_STATIC(std::is_trivially_copyable<T>::value,

with the GNU compilers, versions 4.8.5 and 4.9.2. This should be easily reproduce-able by anyone by building on DAVINCI.

Nick, which version of which compilers are you testing with? While this is clearly in the C++11 spec, it appears to be a low-priority feature for many compilers [1]. I would suggest adding an ifdef that checks very specifically for whatever compiler you're testing with.

I'd also recommend at least making sure your changes build on some of our shared Linux systems (e.g. congaree, DAVINCI, STIC, etc) before pushing. My personal policy for pushing to master is to first run all c/ and cpp/ tests on my macbook and on DAVINCI, and ensure there are no compiler errors or warnings with a reasonably modern GNU compiler (e.g. 4.8 or 4.9 versions).

Please look at this ASAP, as I am unable to build and test the master branch on any systems at the moment.

[1] https://gcc.gnu.org/onlinedocs/gcc-4.8.3/libstdc++/manual/manual/status.html#status.iso.2011

**Comment by DaoWen** [comment]
Shoot. I ran into this same problem on another project. The libstdc++ implementations can lag a bit behind the compilers as far as C++11 support goes. It's very irritating that gcc 4.9 advertises full C++11 compliance when it ships with a non-compliant standard library implementation.

I always test on my macbook (Xcode 7.0 toolchain), and on my linux box (gcc 5.4) before pushing. You shouldn't have any problems building on DAVinCI since it has the same version of gcc available (GCC/5.4.0 module) as the version I'm using on my test machine. Since STIC was decommissioned back in January, we probably don't need to worry about supporting that cluster. I don't have access to congaree, but I'm guessing you have sudo rights and can install a newer gcc/clang toolchain if needed.

As for fixing the gcc 4.9 toolchain support, the easy fix is just to remove the offending static assertions. However, I'd like to keep them since they are a nice sanity check.

I don't know of any way to check for `is_trivially_copyable` support via preprocessor directives. On my other project I worked around this by disabling `is_trivially_copyable` altogether for C++11, and only enabling it if compiling with the C++14. Since that's not an option here, I'll probably need to add an explicit check for this feature in our autoconf scripts. I'll try to get that done tonight.

On a side note, the Dependencies section of the README has always said that gcc 4.9+ is required. We don't seem to be using any gcc 4.9-specific features now, but I was considering using `_Generic` in the C API, which would have been incompatible with 4.8. If we want to maintain 4.8 compatibility, we should update the README to indicate that.

**Comment by agrippa** [comment]
Sorry, I meant NOTS.

GCC 4.9.0 does not support this [1]. Nor does 4.9.1 [2]. Nor does 4.9.2 [3]. Nor does 4.9.3 [4]. These are recent enough releases (August 2016) that they should be supported, and as you point our our README says they are.

I have pushed a fix so that the build is no longer broken. You can take a look at the push to understand how. If you would like to push a follow-on that adds flags for clang and any other compilers you care about, you are welcome to. Please be more careful in the future.

[1] https://gcc.gnu.org/onlinedocs/gcc-4.9.0/libstdc++/manual/manual/status.html#status.iso.2011
[2] https://gcc.gnu.org/onlinedocs/gcc-4.9.1/libstdc++/manual/manual/status.html#status.iso.2011
[3] https://gcc.gnu.org/onlinedocs/gcc-4.9.2/libstdc++/manual/manual/status.html#status.iso.2011
[4] https://gcc.gnu.org/onlinedocs/gcc-4.9.3/libstdc++/manual/manual/status.html#status.iso.2011
